services:
  # Backend FastAPI service
  - type: web
    name: caniparkhere-backend
    runtime: python
    buildCommand: |
      cd backend
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      cd backend
      source venv/bin/activate
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
    healthCheckPath: /health